### ISSUE TITLE
Loading News from the D10 version of Today

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/ucb_campus_news#12]
We'll need to ensure that the campus news block continues to work once the Today site is fully migrated to D10.  

We should be able to get all of the same data from the D10 version via JSON:API.  There's is a full pre-migrated version of the D10 Today site here : https://live-ucbprod-today.pantheonsite.io/ 

Ideally we'll make this block fail gracefully back to the D7 version but attempt to use the D10 version first.  Then once the Today site is live on D10 it will just continue to work for the sites with this block on it.

**Comment by timurtripp** [comment]
At this point the work is mostly done and just needs some testing. I have the URL pointed at https://live-ucbprod-today.pantheonsite.io for testing purposes and will create a draft PR with that URL before changing over to https://www.colorado.edu/today (it can still fallback to loading from D7 if needed).

**Comment by timurtripp** [comment]
Sister issue: CuBoulder/ucb_article_syndication#3
