### ISSUE TITLE
Block is currently ignoring redirect stories.  

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/ucb_campus_news#18]
It looks like the campus news block is currently ignoring stories that have an external URL set.  Apparently this is not the correct behavior and for the Campus News it should be including those in the feed.

**Comment by jcsparks** [comment]
It was not displaying correctly on the homepage.  

Try creating a campus news block on the Developer sandbox and tag it for the CUHomepage unit and see if it matches up with : https://www.colorado.edu/today/syndicate/article/read?unit=1265 

It wasn't matching up on the homepage after we went live and it looked like the articles that were redirects weren't loading.

**Comment by jcsparks** [comment]
The block is only pulling from the D7 version of the site currently.  

The D7 and D10 versions of the campus news block were showing different articles from the same source.

**Comment by timurtripp** [comment]
Once you mentioned this was a problem with the legacy (Drupal 7) Today site API I identified the problem and pushed up a fix in CuBoulder/ucb_campus_news#18.
